import Foundation
import Testing
@testable import RunletCore

struct ShellIntegrationTests {
    let token = "0123456789abcdef0123456789abcdef"

    private func environment(_ launch: TerminalLaunch) -> [String: String] {
        Dictionary(uniqueKeysWithValues: launch.environment.map { entry in
            let parts = entry.split(separator: "=", maxSplits: 1, omittingEmptySubsequences: false)
            return (String(parts[0]), parts.count > 1 ? String(parts[1]) : "")
        })
    }

    private func temporaryDirectory() throws -> URL {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("runlet-shell-integration-\(UUID().uuidString)/Application Support", isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    // MARK: Marker scanner

    @Test func markerIsTheExpectedOSCSequence() {
        #expect(ShellIntegration.readyMarker(token: "abc") == Array("\u{1b}]6973;RunletReady;abc\u{07}".utf8))
        let generated = ShellIntegration.makeToken()
        #expect(generated.count == 32)
        #expect(generated.allSatisfy { $0.isHexDigit })
        #expect(generated != ShellIntegration.makeToken())
    }

    @Test func scannerFindsTheMarkerSplitAtEveryByte() {
        let marker = ShellIntegration.readyMarker(token: token)
        let stream = Array("\u{1b}[?2004l\u{1b}]0;title\u{07}prompt% ".utf8) + marker + Array("\u{1b}[?2004h".utf8)
        for split in 0...stream.count {
            var scanner = ShellIntegration.ReadyScanner(token: token)
            let first = scanner.scan(stream[..<split])
            let second = scanner.scan(stream[split...])
            #expect(second, "split at \(split)")
            #expect(first == (split >= stream.count - 8), "found early at split \(split)")
        }
        var byteByByte = ShellIntegration.ReadyScanner(token: token)
        var foundAt: Int?
        for (index, byte) in stream.enumerated() {
            if byteByByte.scan([byte]), foundAt == nil { foundAt = index }
        }
        #expect(foundAt == stream.count - 9, "found on the marker's last byte (BEL)")
        #expect(byteByByte.found)
    }

    @Test func scannerRecoversFromFalseStarts() {
        let marker = ShellIntegration.readyMarker(token: token)
        var scanner = ShellIntegration.ReadyScanner(token: token)
        // A stray ESC, another OSC 6973 with a different token, and a truncated marker
        // directly followed (no gap) by the real one.
        let other = scanner.scan(Array("\u{1b}\u{1b}]6973;RunletReady;ffff\u{07}".utf8))
        let truncated = scanner.scan(marker.dropLast(5))
        let real = scanner.scan(marker)
        let afterwards = scanner.scan([UInt8]())
        #expect(!other && !truncated && real)
        #expect(afterwards, "stays found")
    }

    @Test func scannerIgnoresOtherTokensAndTruncatedMarkers() {
        var scanner = ShellIntegration.ReadyScanner(token: token)
        let otherToken = scanner.scan(ShellIntegration.readyMarker(token: String(token.reversed())))
        let withoutBEL = scanner.scan(ShellIntegration.readyMarker(token: token).dropLast())
        let stringTerminator = scanner.scan(Array("\u{1b}]6973;RunletReady;\(token)\u{1b}\\".utf8))
        #expect(!otherToken)
        #expect(!withoutBEL, "BEL is part of the marker")
        #expect(!stringTerminator, "only the BEL terminator Runlet writes counts")
        #expect(!scanner.found)
    }

    // MARK: Scripts

    @Test func installWritesTheScriptsAndKeepsThemCurrent() throws {
        let root = try temporaryDirectory()
        defer { try? FileManager.default.removeItem(at: root.deletingLastPathComponent()) }
        try ShellIntegration.install(in: root)
        let zsh = ShellIntegration.zshDirectory(in: root)
        for name in [".zshenv", ".zprofile", ".zshrc", ".zlogin"] {
            let text = try String(contentsOf: zsh.appendingPathComponent(name), encoding: .utf8)
            #expect(text.contains("Generated by Runlet"), "\(name)")
            #expect(!text.contains("echo"), "\(name) must not print during startup")
        }
        let zshrc = try String(contentsOf: zsh.appendingPathComponent(".zshrc"), encoding: .utf8)
        #expect(zshrc.contains(#"builtin source "$_runlet_home/.zshrc""#))
        let zlogin = try String(contentsOf: zsh.appendingPathComponent(".zlogin"), encoding: .utf8)
        #expect(zlogin.contains("_runlet_finish"))
        let bash = try String(contentsOf: ShellIntegration.bashRCFile(in: root), encoding: .utf8)
        #expect(bash.contains(". ~/.bash_profile"))
        #expect(bash.contains("__runlet_ready"))

        // Unchanged files are left alone; a damaged or missing one is rewritten.
        let zshenv = zsh.appendingPathComponent(".zshenv")
        let modified = try FileManager.default.attributesOfItem(atPath: zshenv.path)[.modificationDate] as? Date
        Thread.sleep(forTimeInterval: 0.05)
        try ShellIntegration.install(in: root)
        #expect(try FileManager.default.attributesOfItem(atPath: zshenv.path)[.modificationDate] as? Date == modified)
        try Data("broken".utf8).write(to: zshenv)
        try FileManager.default.removeItem(at: ShellIntegration.bashRCFile(in: root))
        try ShellIntegration.install(in: root)
        #expect(try String(contentsOf: zshenv, encoding: .utf8).contains("_runlet_finish"))
        #expect(FileManager.default.fileExists(atPath: ShellIntegration.bashRCFile(in: root).path))
    }

    @Test func fishInitCommandDefinesAOneShotPromptHandler() {
        let command = ShellIntegration.fishInitCommand(token: token)
        #expect(command.contains("--on-event fish_prompt"))
        #expect(command.contains("functions --erase __runlet_ready"))
        #expect(command.contains(#"printf '\e]6973;RunletReady;%s\a' \#(token)"#))
    }

    @Test func shellsAreRecognizedByExecutableName() {
        #expect(ShellIntegration.Shell(executable: "/bin/zsh") == .zsh)
        #expect(ShellIntegration.Shell(executable: "/opt/homebrew/bin/bash") == .bash)
        #expect(ShellIntegration.Shell(executable: "/opt/homebrew/bin/fish") == .fish)
        #expect(ShellIntegration.Shell(executable: "-zsh") == .zsh)
        #expect(ShellIntegration.Shell(executable: "/bin/sh") == nil)
        #expect(ShellIntegration.Shell(executable: "/usr/local/bin/nu") == nil)
    }

    // MARK: Launch

    private func launch(_ request: TerminalRequest, shell: String, base: [String: String] = ["HOME": "/Users/me", "PATH": "/usr/bin:/bin"], integration: URL? = URL(fileURLWithPath: "/Runlet/Application Support/ShellIntegration")) throws -> TerminalLaunch {
        try TerminalLaunch.make(for: request, shell: shell, baseEnvironment: base, home: NSTemporaryDirectory(), language: "en_US.UTF-8", shellIntegration: integration, readyToken: token)
    }

    @Test func zshCommandTabsStartWithRunletsZdotdir() throws {
        let command = TerminalRequest(title: "inspire", commandLine: "php artisan inspire")
        let plain = try launch(command, shell: "/bin/zsh")
        #expect(plain.argv0 == "-zsh", "still a login shell")
        #expect(plain.arguments.isEmpty)
        #expect(plain.readyToken == token)
        #expect(plain.pendingInput == "php artisan inspire\r")
        var env = environment(plain)
        #expect(env["ZDOTDIR"] == "/Runlet/Application Support/ShellIntegration/zsh")
        #expect(env["RUNLET_SHELL_READY_TOKEN"] == token)
        #expect(env["RUNLET_USER_ZDOTDIR"] == nil, "no inherited ZDOTDIR: the scripts use HOME")

        let custom = try launch(command, shell: "/bin/zsh", base: ["HOME": "/Users/me", "ZDOTDIR": "/Users/me/.config/zsh"])
        env = environment(custom)
        #expect(env["ZDOTDIR"] == "/Runlet/Application Support/ShellIntegration/zsh")
        #expect(env["RUNLET_USER_ZDOTDIR"] == "/Users/me/.config/zsh")

        // A ZDOTDIR that already points at Runlet's files is not the user's.
        let looped = try launch(command, shell: "/bin/zsh", base: ["HOME": "/Users/me", "ZDOTDIR": "/Runlet/Application Support/ShellIntegration/zsh"])
        #expect(environment(looped)["RUNLET_USER_ZDOTDIR"] == nil)
    }

    @Test func bashCommandTabsUseTheRCFile() throws {
        let launch = try launch(TerminalRequest(title: "x", commandLine: "composer test"), shell: "/opt/homebrew/bin/bash")
        #expect(launch.argv0 == "bash", "--rcfile applies only to non-login shells")
        #expect(launch.arguments == ["--rcfile", "/Runlet/Application Support/ShellIntegration/bash/runlet.bash", "-i"])
        #expect(launch.readyToken == token)
        #expect(environment(launch)["RUNLET_SHELL_READY_TOKEN"] == token)
        #expect(environment(launch)["ZDOTDIR"] == nil)
    }

    @Test func fishCommandTabsUseAnInitCommand() throws {
        let launch = try launch(TerminalRequest(title: "x", commandLine: "ls"), shell: "/opt/homebrew/bin/fish")
        #expect(launch.argv0 == "-fish")
        #expect(launch.arguments == ["--init-command", ShellIntegration.fishInitCommand(token: token)])
        #expect(launch.readyToken == token)
        #expect(environment(launch)["RUNLET_SHELL_READY_TOKEN"] == nil, "the token is in the init command")
    }

    @Test func plainShellsAndOtherShellsAreUnchanged() throws {
        // No command: exactly the plain login shell.
        let base = ["HOME": "/Users/me", "ZDOTDIR": "/Users/me/.config/zsh", "RUNLET_SHELL_READY_TOKEN": "leaked", "RUNLET_USER_ZDOTDIR": "/leaked"]
        for shell in ["/bin/zsh", "/bin/bash", "/opt/homebrew/bin/fish"] {
            let plain = try launch(TerminalRequest(title: "shell"), shell: shell, base: base)
            #expect(plain.argv0 == "-" + (shell as NSString).lastPathComponent)
            #expect(plain.arguments.isEmpty)
            #expect(plain.readyToken == nil)
            let env = environment(plain)
            #expect(env["ZDOTDIR"] == "/Users/me/.config/zsh")
            #expect(env["RUNLET_SHELL_READY_TOKEN"] == nil && env["RUNLET_USER_ZDOTDIR"] == nil, "never inherited")
        }
        // Shells without an integration, no installed scripts, or a direct executable.
        let command = TerminalRequest(title: "x", commandLine: "ls")
        let sh = try launch(command, shell: "/bin/sh")
        #expect(sh.argv0 == "-sh" && sh.arguments.isEmpty && sh.readyToken == nil)
        let missing = try launch(command, shell: "/bin/zsh", integration: nil)
        #expect(missing.argv0 == "-zsh" && missing.readyToken == nil && environment(missing)["ZDOTDIR"] == nil)
        let direct = try TerminalLaunch.make(
            for: TerminalRequest(title: "x", commandLine: "ls", executable: ["docker", "exec", "-it", "c", "sh"]),
            shell: "/bin/zsh", baseEnvironment: [:], home: NSTemporaryDirectory(), language: "C",
            shellIntegration: URL(fileURLWithPath: "/Runlet"), resolveExecutable: { _ in "/usr/local/bin/docker" }
        )
        #expect(direct.readyToken == nil)
        #expect(direct.pendingInput == "ls\r")
    }

    @Test func requestsKnowWhetherTheyRunACommand() {
        #expect(!TerminalRequest(title: "zsh").isCommand)
        #expect(!TerminalRequest(title: "app shell", executable: ["docker", "exec", "-it", "c", "sh"]).isCommand)
        #expect(TerminalRequest(title: "inspire", commandLine: "php artisan inspire").isCommand)
        #expect(TerminalRequest(title: "migrate", executable: ["docker", "exec", "-it", "c", "sh", "-lc", "php artisan migrate"], isCommand: true).isCommand)
    }
}
