import Foundation
import Testing
@testable import RunletCore

/// Promote a snippet (#39): Artisan commands, Pest tests, and PHPUnit tests generated from a
/// snippet, and the names and project layout they use. `SnippetPromotionPHPTests` checks the
/// generated files with a local PHP.
struct SnippetPromotionTests {
    private func command(_ code: String, title: String = "Refund order", className: String = "RefundOrder", strictTypes: Bool = false, contextCode: String? = nil, description: String? = nil) -> SnippetPromotion.Output {
        SnippetPromotion.artisanCommand(SnippetPromotion.Source(code: code, contextCode: contextCode, title: title, description: description, strictTypes: strictTypes), className: className, namespace: "App\\Console\\Commands", commandName: SnippetPromotion.commandName(forClass: className))
    }

    private func pest(_ code: String, title: String = "Refund order") -> SnippetPromotion.Output {
        SnippetPromotion.test(SnippetPromotion.Source(code: code, title: title), style: .pest)
    }

    private func phpunit(_ code: String, title: String = "Refund order") -> SnippetPromotion.Output {
        SnippetPromotion.test(SnippetPromotion.Source(code: code, title: title), style: .phpunit, className: "RefundOrderTest", namespace: "Tests\\Feature", baseClass: "Tests\\TestCase")
    }

    // MARK: Whole files

    @Test func writesAnArtisanCommand() {
        let output = command("""
        <?php

        use App\\Models\\Order;

        $order = Order::findOrFail(42); //?
        $order->refund();
        $order->fresh()->status
        """)
        #expect(output.notes.isEmpty)
        #expect(output.source == """
        <?php

        namespace App\\Console\\Commands;

        use App\\Models\\Order;
        use Illuminate\\Console\\Command;

        class RefundOrder extends Command
        {
            /**
             * The name and signature of the console command.
             *
             * @var string
             */
            protected $signature = 'app:refund-order';

            /**
             * The console command description.
             *
             * @var string
             */
            protected $description = 'Refund order';

            /**
             * Execute the console command.
             *
             * Generated by Runlet from a snippet: review it before you run it.
             */
            public function handle()
            {
                $order = Order::findOrFail(42);
                $order->refund();
                dump($order->fresh()->status);
            }
        }

        """)
    }

    @Test func writesAPestTest() {
        let output = pest("""
        use App\\Models\\User;

        $user = User::factory()->create();
        $user->posts()->count();
        """, title: "User's posts")
        #expect(output.source == """
        <?php

        use App\\Models\\User;

        test('User\\'s posts', function () {
            $user = User::factory()->create();
            $result = $user->posts()->count();

            // TODO: Assert the snippet's result, for example: expect($result)->toBe(...);
        });

        """)
    }

    @Test func writesAPHPUnitTest() {
        let output = phpunit("""
        <?php
        $total = 1 + 2;
        """)
        #expect(output.source == """
        <?php

        namespace Tests\\Feature;

        use Tests\\TestCase;

        class RefundOrderTest extends TestCase
        {
            public function test_refund_order()
            {
                $total = 1 + 2;

                // TODO: Assert the snippet's result, for example: $this->assertSame(..., $total);
            }
        }

        """)
    }

    // MARK: The result

    @Test func dumpsTheResultInACommand() {
        // The last expression statement, with or without its semicolon.
        #expect(command("$a = 1;\n$a + 1").source.contains("        $a = 1;\n        dump($a + 1);\n    }"))
        #expect(command("$a = 1;\n$a + 1; // the sum").source.contains("dump($a + 1); // the sum\n"))
        // A final return.
        #expect(command("$a = 1;\nreturn $a * 2;").source.contains("        dump($a * 2);\n    }"))
        // An assignment keeps its variable.
        #expect(command("$a = 1;\n$b = $a + 1").source.contains("        $b = $a + 1;\n        dump($b);\n    }"))
        #expect(command("$items = [];\n$items[] = 3;").source.contains("dump($items[] = 3);"))
        #expect(command("$n = 1;\n$n += 2;").source.contains("        $n += 2;\n        dump($n);"))
        #expect(command("$n = 1;\n$n == 2;").source.contains("dump($n == 2);"))
        // A multi-line chain keeps its lines.
        #expect(command("User::query()\n    ->where('active', true)\n    ->count()").source.contains("        dump(User::query()\n            ->where('active', true)\n            ->count());"))
    }

    @Test func leavesStatementsWithoutAResult() {
        for code in [
            "foreach ([1, 2] as $i) {\n    echo $i;\n}",
            "if (true) {\n    $x = 1;\n} else {\n    $x = 2;\n}",
            "echo 'hi';",
            "function twice($x) { return 2 * $x; }",
            "return;",
            "exit(0);",
            "dump($value);",
            "dd(User::first());",
            "try {\n    risky();\n} catch (Exception $e) {\n    report($e);\n} finally {\n    cleanUp();\n}",
            "do {\n    $i++;\n} while ($i < 3);",
            "class Thing {}",
            "static $counter = 0;",
            "?>\n<p>Hello</p>",
        ] {
            #expect(!command(code).source.contains("dump(") || code.contains("dump("), "\(code)")
            #expect(pest(code).source.contains("// TODO: Add assertions."), "\(code)")
        }
        // A closure or a static call is an expression.
        #expect(command("function () { return 1; };").source.contains("dump(function () { return 1; });"))
        #expect(command("static fn () => 1;").source.contains("dump(static fn () => 1);"))
        #expect(command("Cache::flush();").source.contains("dump(Cache::flush());"))
    }

    @Test func assignsTheResultInATest() {
        #expect(pest("$a = 1;\nreturn $a + 1;").source.contains("    $result = $a + 1;\n\n    // TODO: Assert the snippet's result, for example: expect($result)->toBe(...);"))
        // A snippet that already uses $result.
        #expect(pest("$result = 1;\n$result + 1").source.contains("$result2 = $result + 1;"))
        // `and`/`or` bind more loosely than `=`.
        #expect(pest("$a = true;\n$a and false").source.contains("$result = ($a and false);"))
        #expect(phpunit("$a = 1;\n$a").source.contains("$result = $a;\n\n        // TODO: Assert the snippet's result, for example: $this->assertSame(..., $result);"))
    }

    // MARK: Imports and declarations

    @Test func liftsImportsAndDeclarations() {
        let output = command("""
        <?php
        declare(strict_types=1);

        use function App\\helper;
        use App\\Models\\{User, Order as PurchaseOrder};
        use \\Carbon\\Carbon;
        use const App\\LIMIT;

        Carbon::now();
        """)
        #expect(output.source.contains("""
        <?php

        declare(strict_types=1);

        namespace App\\Console\\Commands;

        use App\\Models\\{User, Order as PurchaseOrder};
        use Carbon\\Carbon;
        use Illuminate\\Console\\Command;
        use function App\\helper;
        use const App\\LIMIT;

        class RefundOrder extends Command
        """))
        #expect(output.source.contains("    {\n        dump(Carbon::now());\n    }"))
        // strict_types from the target's setting, unless the snippet declares otherwise.
        #expect(command("1;", strictTypes: true).source.contains("declare(strict_types=1);"))
        #expect(!command("declare(strict_types=0);\n1;", strictTypes: true).source.contains("strict_types"))
    }

    @Test func importsTheWholeTabsImportsForASelection() {
        let tab = "<?php\nuse App\\Models\\User;\nuse App\\Models\\Order;\n\n$user = User::first();\nOrder::count();"
        let output = command("Order::count();", contextCode: tab)
        #expect(output.source.contains("use App\\Models\\Order;\nuse App\\Models\\User;\nuse Illuminate\\Console\\Command;"))
        #expect(output.source.contains("dump(Order::count());"))
    }

    @Test func dropsNamespacesWithANote() {
        let statement = command("namespace App\\Scratch;\n\nuse App\\Models\\User;\nUser::count();")
        #expect(statement.source.contains("        // TODO: Runlet removed the snippet's namespace App\\Scratch: the class has its own.\n\n        dump(User::count());"))
        #expect(statement.notes == ["Runlet removed the snippet's namespace App\\Scratch: the class has its own."])
        let block = command("namespace Scratch {\n    use App\\Models\\User;\n    User::count();\n}")
        #expect(block.source.contains("use App\\Models\\User;"))
        #expect(block.source.contains("        dump(User::count());\n    }"))
        #expect(!block.source.contains("namespace Scratch {"))
        #expect(block.notes == ["Runlet removed the snippet's namespace Scratch: the class has its own."])
    }

    @Test func movesDeclarationsBeforeTheClass() {
        let code = """
            echo twice(2);
            $box = new Box(3);

            #[\\Deprecated]
            function twice(int $x): int
            {
                return 2 * $x;
            }

            final class Box
            {
                public function __construct(public int $size) {}
            }

            const LIMIT = 10;
            enum Size: int { case Small = 1; }
            $box->size + LIMIT
        """
        let output = command(code)
        #expect(output.source.contains("""
        use Illuminate\\Console\\Command;

        #[\\Deprecated]
        function twice(int $x): int
        {
            return 2 * $x;
        }

        final class Box
        {
            public function __construct(public int $size) {}
        }

        const LIMIT = 10;

        enum Size: int { case Small = 1; }

        class RefundOrder extends Command
        """))
        #expect(output.source.contains("""
            {
                echo twice(2);
                $box = new Box(3);

                dump($box->size + LIMIT);
            }
        """))
        #expect(pest(code).source.contains("enum Size: int { case Small = 1; }\n\ntest('Refund order', function () {"))
        // Closures, anonymous classes, and conditional declarations stay.
        let kept = command("$f = function () {};\nif (!function_exists('x')) {\n    function x() {}\n}\n$o = new class {};")
        #expect(kept.source.contains("        $f = function () {};\n        if (!function_exists('x')) {\n            function x() {}\n        }\n        $o = new class {};\n        dump($o);"))
    }

    @Test func avoidsBaseClassNameClashes() {
        let output = command("use Symfony\\Component\\Console\\Command\\Command;\nCommand::SUCCESS;")
        #expect(output.source.contains("class RefundOrder extends \\Illuminate\\Console\\Command"))
        #expect(!output.source.contains("use Illuminate\\Console\\Command;"))
        #expect(command("1;", className: "Command").source.contains("class Command extends \\Illuminate\\Console\\Command"))
        #expect(SnippetPromotion.conflictingImport(className: "Order", code: "use App\\Models\\Order;") == "use App\\Models\\Order;")
        #expect(SnippetPromotion.conflictingImport(className: "Order", code: "use App\\Models\\{Order as O, User};") == nil)
        #expect(SnippetPromotion.conflictingImport(className: "User", code: "x();", contextCode: "use App\\Models\\{Order as O, User};") == "use App\\Models\\{Order as O, User};")
        #expect(SnippetPromotion.conflictingImport(className: "Helper", code: "use function App\\helper;") == nil)
    }

    // MARK: Magic comments, strings, indentation

    @Test func removesMagicCommentsOnly() {
        let output = command("""
        $a = 2; //?
        $b = $a * 3 /*?*/ + 1;
        /*?.*/
        $c = collect([1, 2]) /*?->count()*/ /*??->first()*/;
        // a note //? stays
        # not magic #?
        $d = '//? in a string';
        //? note
        $c
        """)
        #expect(output.source.contains("""
                $a = 2;
                $b = $a * 3 + 1;
                $c = collect([1, 2]);
                // a note //? stays
                # not magic #?
                $d = '//? in a string';
                //? note
                dump($c);
        """))
    }

    @Test func keepsStringValuesWhenIndenting() {
        let code = """
        $name = 'World';
        $heredoc = <<<EOT
            Hello $name
              {$name}s
            EOT;
        $nowdoc = <<<'TXT'
        line one
          line two
        TXT;
        $multi = 'first
          second';
        $double = "a {$name["x"]} \\" b
        c";
        strlen($heredoc . $nowdoc . $multi . $double)
        """
        let source = command(code).source
        #expect(source.contains("        $heredoc = <<<EOT\n    Hello $name\n      {$name}s\n    EOT;\n        $nowdoc = <<<'TXT'\nline one\n  line two\nTXT;\n"))
        #expect(source.contains("        $multi = 'first\n  second';\n"))
        #expect(source.contains("        $double = \"a {$name[\"x\"]} \\\" b\nc\";\n"))
        #expect(source.contains("        dump(strlen($heredoc . $nowdoc . $multi . $double));"))
    }

    @Test func reindentsUniformlyIndentedCode() {
        let output = pest("    $a = 1;\n    if ($a) {\n        $a++;\n    }\n\n\n    $a")
        #expect(output.source.contains("test('Refund order', function () {\n    $a = 1;\n    if ($a) {\n        $a++;\n    }\n\n    $result = $a;"))
    }

    @Test func returnsToPHPAfterInlineHTML() {
        let output = command("$name = 'x';\n?>\n<p><?= $name ?></p>\n")
        // `<?php` after inline HTML stays at the start of its line: spaces before it would be output.
        #expect(output.source.contains("        $name = 'x';\n        ?>\n<p><?= $name ?></p>\n<?php\n    }"))
    }

    @Test func notesUnterminatedCodeAndRunletHelpers() {
        #expect(command("$a = 'open").notes.contains("A string, comment, or heredoc in the snippet doesn't end: check the generated code."))
        #expect(command("Runlet\\bench(fn () => 1);").notes.contains { $0.contains("Runlet\\bench()") })
    }

    // MARK: Inputs

    @Test func turnsInputsIntoArgumentsAndOptions() {
        let output = command("""
        /**
         * Refund an order.
         *
         * @input int $orderId "Order ID"
         * @input float $amount "Amount {EUR}" = 9.5
         * @input string $reason "Reason" = "duplicate" {duplicate, fraudulent}
         * @input bool $notify "Email the customer" = true
         * @input bool $dryRun
         * @input string $env = "it's"
         */
        $orderId = 0;
        refund($orderId, $amount, $reason, $notify, $dryRun, $env);
        """)
        #expect(output.source.contains("""
            protected $signature = 'app:refund-order
                                    {orderId : Order ID}
                                    {--amount= : Amount (EUR) (default: 9.5)}
                                    {--reason= : Reason (one of duplicate, fraudulent; default: duplicate)}
                                    {--no-notify : Turn off: Email the customer}
                                    {--dry-run : dryRun}
                                    {--env-2= : env (default: it\\'s)}';
        """))
        #expect(output.source.contains("""
                /**
                 * Refund an order.
                 */
                $amount = (float) ($this->option('amount') ?? 9.5);
                $reason = $this->option('reason') ?? 'duplicate';
                $notify = ! $this->option('no-notify');
                $dryRun = (bool) $this->option('dry-run');
                $env = $this->option('env-2') ?? 'it\\'s';

                $orderId = (int) $this->argument('orderId');
                dump(refund($orderId, $amount, $reason, $notify, $dryRun, $env));
        """))
    }

    @Test func givesTestsTheInputsDefaults() {
        let output = pest("""
        /**
         * @input int $orderId "Order ID"
         * @input int $limit = 5
         * @input string $note
         * @input bool $dryRun
         * @input nonsense $x
         */
        $note = 'kept';
        $orderId + $limit
        """)
        #expect(output.notes == [
            "Runlet couldn't read @input nonsense $x: “nonsense” is not an input type. Use int, float, string, or bool.",
            "Choose a test value for $orderId (Order ID): its input has no default.",
        ])
        #expect(output.source.contains("""
        test('Refund order', function () {
            // TODO: Runlet couldn't read @input nonsense $x: “nonsense” is not an input type. Use int, float, string, or bool.
            // TODO: Choose a test value for $orderId (Order ID): its input has no default.

            $orderId = 0;
            $limit = 5;
            $dryRun = false;

            $note = 'kept';
            $result = $orderId + $limit;
        """))
    }

    // MARK: Escaping

    @Test func escapesTitlesAndComments() {
        let output = command("1;", title: "It's a \\ test $x\nsecond line", description: nil)
        #expect(output.source.contains("protected $description = 'It\\'s a \\\\ test $x second line';"))
        #expect(pest("1;", title: "Say 'hi' to $user").source.contains("test('Say \\'hi\\' to $user', function () {"))
        #expect(SnippetPromotion.commentText("ends ?> here\nnext") == "ends ? > here next")
        #expect(command("1;", description: "Refunds one order").source.contains("protected $description = 'Refunds one order';"))
    }

    // MARK: Names

    @Test func makesNames() {
        #expect(SnippetPromotion.className(fromTitle: "refund order #42") == "RefundOrder42")
        #expect(SnippetPromotion.className(fromTitle: "scratch.php") == "Scratch")
        #expect(SnippetPromotion.className(fromTitle: "2024 report") == "Snippet2024Report")
        #expect(SnippetPromotion.className(fromTitle: "Zählung der Bestellungen") == "ZahlungDerBestellungen")
        #expect(SnippetPromotion.className(fromTitle: "  ") == "Snippet")
        #expect(SnippetPromotion.className(fromTitle: "list") == "ListCommand")
        #expect(SnippetPromotion.className(fromTitle: "refund order", suffix: "Test") == "RefundOrderTest")
        #expect(SnippetPromotion.className(fromTitle: "Order test", suffix: "Test") == "OrderTest")
        #expect(SnippetPromotion.className(fromTitle: "test", suffix: "Test") == "SnippetTest")

        #expect(SnippetPromotion.kebab("RefundOrder") == "refund-order")
        #expect(SnippetPromotion.kebab("HTTPReport") == "http-report")
        #expect(SnippetPromotion.kebab("orderId") == "order-id")
        #expect(SnippetPromotion.kebab("order_id") == "order-id")
        #expect(SnippetPromotion.kebab("Order2Refund") == "order2-refund")
        #expect(SnippetPromotion.commandName(forClass: "RefundOrder") == "app:refund-order")
        #expect(SnippetPromotion.commandName(forClass: "RefundOrder", flavor: .laravelZero) == "refund-order")
        #expect(SnippetPromotion.testMethodName(fromTitle: "Refund order #42") == "test_refund_order_42")
        #expect(SnippetPromotion.testMethodName(fromTitle: "") == "test_snippet")

        #expect(SnippetPromotion.isValidClassName("RefundOrder"))
        #expect(SnippetPromotion.isValidClassName("_Refund2"))
        #expect(!SnippetPromotion.isValidClassName("2Refund"))
        #expect(!SnippetPromotion.isValidClassName("Refund Order"))
        #expect(!SnippetPromotion.isValidClassName("Refund-Order"))
        #expect(!SnippetPromotion.isValidClassName("Class"))
        #expect(!SnippetPromotion.isValidClassName(""))
    }

    // MARK: Project layout

    @Test func readsTheProjectLayout() throws {
        let composer = Data("""
        {
            "require": {"php": "^8.2", "laravel/framework": "^12.0"},
            "require-dev": {"pestphp/pest": "^3.0"},
            "autoload": {"psr-4": {"App\\\\": "app/", "Database\\\\Factories\\\\": "database/factories/"}},
            "autoload-dev": {"psr-4": {"Tests\\\\": ["tests/"]}}
        }
        """.utf8)
        let layout = SnippetPromotion.ProjectLayout(composerJSON: composer, hasTestCase: true)
        #expect(layout.usesPest)
        #expect(layout.testStyle == .pest)
        #expect(layout.namespace(forDirectory: "app/Console/Commands") == "App\\Console\\Commands")
        #expect(layout.namespace(forDirectory: "app") == "App")
        #expect(layout.namespace(forDirectory: "tests/Feature/Orders") == "Tests\\Feature\\Orders")
        #expect(layout.namespace(forDirectory: "database/factories") == "Database\\Factories")
        #expect(layout.namespace(forDirectory: "app/my-folder") == nil)
        #expect(layout.namespace(forDirectory: "scripts") == nil)
        #expect(layout.testBaseClass == "Tests\\TestCase")

        let plain = SnippetPromotion.ProjectLayout(composerJSON: Data(#"{"require-dev": {"phpunit/phpunit": "^11"}, "autoload": {"psr-4": {"Acme\\": ""}}}"#.utf8))
        #expect(!plain.usesPest)
        #expect(plain.testStyle == .phpunit)
        #expect(plain.namespace(forDirectory: "") == "Acme")
        #expect(plain.namespace(forDirectory: "src/Jobs") == "Acme\\src\\Jobs")
        #expect(plain.testBaseClass == "PHPUnit\\Framework\\TestCase")
        #expect(SnippetPromotion.ProjectLayout(composerJSON: nil, hasPestFiles: true).usesPest)
        #expect(SnippetPromotion.ProjectLayout(composerJSON: Data("not json".utf8)).psr4.isEmpty)

        let root = URL(fileURLWithPath: "/tmp/project", isDirectory: true)
        #expect(SnippetPromotion.relativeDirectory(of: root.appendingPathComponent("app/Console/Commands/Refund.php"), in: root) == "app/Console/Commands")
        #expect(SnippetPromotion.relativeDirectory(of: root.appendingPathComponent("Refund.php"), in: root) == "")
        #expect(SnippetPromotion.relativeDirectory(of: URL(fileURLWithPath: "/tmp/other/Refund.php"), in: root) == nil)
    }

    @Test func picksTheCommandFlavor() {
        #expect(SnippetPromotion.CommandFlavor(framework: "laravel") == .laravel)
        #expect(SnippetPromotion.CommandFlavor(framework: "lumen") == .laravel)
        #expect(SnippetPromotion.CommandFlavor(framework: "laravel-zero") == .laravelZero)
        #expect(SnippetPromotion.CommandFlavor(framework: "symfony") == nil)
        #expect(SnippetPromotion.CommandFlavor(framework: nil) == nil)
        let zero = SnippetPromotion.artisanCommand(SnippetPromotion.Source(code: "1;", title: "Ping"), className: "Ping", namespace: "App\\Commands", commandName: "ping", flavor: .laravelZero)
        #expect(zero.source.contains("use LaravelZero\\Framework\\Commands\\Command;"))
        #expect(zero.source.contains("protected $signature = 'ping';"))
    }

    // MARK: Statements

    @Test func splitsTopLevelStatements() {
        let scan = PHPCodeScan("<?php\nif ($a) { x(); } elseif ($b) { y(); } else { z(); }\n$f = function () { return 1; };\nmatch($a) { 1 => 'one', default => 'other' };\nclass A { function b() {} }\nfoo()")
        let statements = scan.statements(from: 1)
        #expect(statements.map(\.end) == [.brace, .semicolon, .semicolon, .brace, .none])
        #expect(statements.map { scan.isExpressionStatement($0) } == [false, true, true, false, true])
        #expect(scan.assignedVariable(statements[1]) == "$f")
    }
}
