import Foundation
import RunletCore

/// Identifies one PHPantom server session. Tabs with equal keys share a server; different
/// keys never share suggestions.
public struct LanguageWorkspace: Sendable, Hashable {
    public enum Kind: String, Sendable, Hashable {
        /// A real project root (local project, sandbox, or mapped Docker checkout).
        case project
        /// No local source: core PHP completion only (unmapped Docker containers and SSH hosts).
        case basic
    }

    public var kind: Kind
    public var rootPath: String
    /// Optional PHP language-level override (e.g. "8.2"); nil infers from composer.json.
    public var phpVersion: String?

    public init(kind: Kind, rootPath: String, phpVersion: String? = nil) {
        self.kind = kind
        self.rootPath = rootPath
        self.phpVersion = phpVersion
    }

    public var rootURL: URL { URL(fileURLWithPath: rootPath, isDirectory: true) }

    /// Limitations to show the user (missing vendor, unmapped container, ...).
    public func sourceLimitations() -> [String] {
        let fm = FileManager.default
        switch kind {
        case .basic:
            return ["No local source is mapped, so only built-in PHP completion is available. Map a local checkout in the profile for project completion."]
        case .project:
            var notes: [String] = []
            if !fm.fileExists(atPath: rootPath) {
                notes.append("The source directory \(rootPath) does not exist.")
            } else if fm.fileExists(atPath: rootURL.appendingPathComponent("composer.json").path),
                      !fm.fileExists(atPath: rootURL.appendingPathComponent("vendor/autoload.php").path) {
                notes.append("vendor/ is not installed in the local checkout, so dependency completion is limited (it may exist only inside the container or on the server).")
            }
            return notes
        }
    }
}

public enum LanguageServerState: Sendable, Equatable {
    case stopped
    case starting
    case ready(serverVersion: String?)
    case restarting(attempt: Int)
    case failed(String)

    public var isReady: Bool {
        if case .ready = self { return true }
        return false
    }
}

/// Diagnostics for one open document, in LSP coordinates.
public struct DiagnosticsUpdate: Sendable {
    public var uri: String
    public var version: Int?
    public var diagnostics: [LSPDiagnostic]
}

/// Settings Runlet writes into an app-owned PHPantom config directory (passed via
/// XDG_CONFIG_HOME, which PHPantom reads as its *global* config). User repositories and
/// the user's own global config are never modified. A project's `.phpantom.toml` still
/// merges on top, as PHPantom documents.
enum PHPantomConfig {
    static func toml(phpVersion: String?) -> String {
        var lines = [
            "# Generated by Runlet for its embedded PHPantom sessions. Do not edit.",
            "# External analyzers and formatters are disabled so nothing runs implicitly",
            "# (they would need host PHP and container-aware routing).",
        ]
        if let phpVersion {
            lines += ["", "[php]", "version = \"\(phpVersion)\""]
        }
        lines += [
            "",
            "[diagnostics]",
            "workspace = false",
            "workspace-external = false",
            "",
            "[formatting]",
            "pint = \"\"",
            "php-cs-fixer = \"\"",
            "phpcbf = \"\"",
            "",
            "[phpstan]",
            "command = \"\"",
            "",
            "[phpcs]",
            "command = \"\"",
            "",
            "[mago]",
            "command = \"\"",
            "",
        ]
        return lines.joined(separator: "\n")
    }

    /// Creates (or refreshes) a config home for one workspace and returns its path.
    static func prepareHome(base: URL, workspace: LanguageWorkspace) throws -> URL {
        let key = "\(workspace.kind.rawValue)|\(workspace.rootPath)|\(workspace.phpVersion ?? "")"
        let digest = key.utf8.reduce(UInt64(14_695_981_039_346_656_037)) { ($0 ^ UInt64($1)) &* 1_099_511_628_211 }
        let home = base.appendingPathComponent("config-\(String(digest, radix: 16))", isDirectory: true)
        let directory = home.appendingPathComponent("phpantom_lsp", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        try toml(phpVersion: workspace.phpVersion).write(to: directory.appendingPathComponent(".phpantom.toml"), atomically: true, encoding: .utf8)
        return home
    }
}

/// One PHPantom process for one workspace, with crash recovery and document re-sync.
public actor LanguageServerSession {
    public nonisolated let workspace: LanguageWorkspace
    private let binary: URL
    private let configBase: URL
    /// Whether adjusted in-memory copies of Eloquent model files are opened (`EloquentOverlay`).
    public nonisolated let modelOverlays: Bool

    private var connection: LSPConnection?
    private var openDocuments: [String: (text: String, version: Int)] = [:]
    private var restartAttempts = 0
    private var stoppedByClient = false
    private var stateContinuations: [UUID: AsyncStream<LanguageServerState>.Continuation] = [:]
    private var diagnosticsContinuations: [UUID: AsyncStream<DiagnosticsUpdate>.Continuation] = [:]
    private var startTask: Task<Void, Never>?
    public private(set) var state: LanguageServerState = .stopped
    public private(set) var serverCapabilities: JSONValue = .null
    public private(set) var lastStartupMs: Int?
    /// URIs of the model copies opened at the last start (see `EloquentOverlay`).
    public private(set) var overlayDocumentURIs: [String] = []

    public init(workspace: LanguageWorkspace, binary: URL, configBase: URL, modelOverlays: Bool = true) {
        self.workspace = workspace
        self.binary = binary
        self.configBase = configBase
        self.modelOverlays = modelOverlays
    }

    // MARK: Observation

    public func stateUpdates() -> AsyncStream<LanguageServerState> {
        let (stream, continuation) = AsyncStream<LanguageServerState>.makeStream()
        let id = UUID()
        stateContinuations[id] = continuation
        continuation.yield(state)
        continuation.onTermination = { [weak self] _ in Task { await self?.removeStateObserver(id) } }
        return stream
    }

    public func diagnosticsUpdates() -> AsyncStream<DiagnosticsUpdate> {
        let (stream, continuation) = AsyncStream<DiagnosticsUpdate>.makeStream()
        let id = UUID()
        diagnosticsContinuations[id] = continuation
        continuation.onTermination = { [weak self] _ in Task { await self?.removeDiagnosticsObserver(id) } }
        return stream
    }

    private func removeStateObserver(_ id: UUID) { stateContinuations[id] = nil }
    private func removeDiagnosticsObserver(_ id: UUID) { diagnosticsContinuations[id] = nil }

    private func setState(_ newState: LanguageServerState) {
        state = newState
        stateContinuations.values.forEach { $0.yield(newState) }
    }

    // MARK: Lifecycle

    /// Starts the server if needed and waits until it is initialized.
    public func start() async {
        if state.isReady { return }
        if let startTask {
            await startTask.value
            return
        }
        let task = Task { await self.launch() }
        startTask = task
        await task.value
        startTask = nil
    }

    private func launch() async {
        stoppedByClient = false
        setState(restartAttempts > 0 ? .restarting(attempt: restartAttempts) : .starting)
        let started = ContinuousClock.now
        do {
            let home = try PHPantomConfig.prepareHome(base: configBase, workspace: workspace)
            try FileManager.default.createDirectory(at: workspace.rootURL, withIntermediateDirectories: true)
            var environment = ExecutableLocator.minimalEnvironment()
            environment["XDG_CONFIG_HOME"] = home.path
            var spec = ProcessSpec(executable: binary.path, arguments: ["--stdio"], environment: environment, workingDirectory: workspace.rootPath, newProcessGroup: true)
            spec.keepStdinOpen = true
            let process = try SupervisedProcess.launch(spec)
            let connection = LSPConnection(process: process, onNotification: { [weak self] method, params in
                Task { await self?.handleNotification(method, params) }
            }, onClose: { [weak self] in
                Task { await self?.connectionClosed(pid: process.pid) }
            })
            self.connection = connection
            let rootURI = workspace.rootURL.absoluteString
            let result = try await connection.request("initialize", Self.initializeParams(rootURI: rootURI, name: workspace.rootURL.lastPathComponent), timeout: .seconds(30))
            serverCapabilities = result["capabilities"] ?? .null
            connection.notify("initialized", .object([:]))
            // Adjusted copies of model files, read fresh at every start (#55). Never written to disk.
            let overlays = workspace.kind == .project && modelOverlays
                ? await Task.detached { [root = workspace.rootURL] in EloquentOverlay.documents(root: root) }.value
                : []
            for overlay in overlays {
                connection.notify("textDocument/didOpen", Self.didOpenParams(uri: overlay.uri, text: overlay.text, version: 1))
            }
            overlayDocumentURIs = overlays.map(\.uri)
            // Runlet's own snippet API (#196): `\Runlet\notice()`, `bench()`, `Inspector`, … complete
            // and hover in every workspace. In memory only, like the model copies.
            connection.notify("textDocument/didOpen", Self.didOpenParams(uri: RunletAPIStub.uri(root: workspace.rootURL), text: RunletAPIStub.source, version: 1))
            for (uri, document) in openDocuments {
                connection.notify("textDocument/didOpen", Self.didOpenParams(uri: uri, text: document.text, version: document.version))
            }
            let elapsed = ContinuousClock.now - started
            lastStartupMs = Int(elapsed.components.seconds * 1000 + elapsed.components.attoseconds / 1_000_000_000_000_000)
            setState(.ready(serverVersion: result["serverInfo"]?["version"]?.stringValue))
        } catch {
            connection = nil
            setState(.failed("PHPantom could not start: \(error)"))
        }
    }

    static func initializeParams(rootURI: String, name: String) -> JSONValue {
        .object([
            "processId": .number(Double(ProcessInfo.processInfo.processIdentifier)),
            "clientInfo": .object(["name": .string("Runlet")]),
            "rootUri": .string(rootURI),
            "workspaceFolders": .array([.object(["uri": .string(rootURI), "name": .string(name)])]),
            "capabilities": .object([
                "general": .object(["positionEncodings": .array([.string("utf-16")])]),
                "textDocument": .object([
                    "synchronization": .object(["didSave": .bool(false)]),
                    "completion": .object([
                        "completionItem": .object([
                            "snippetSupport": .bool(false),
                            "documentationFormat": .array([.string("markdown"), .string("plaintext")]),
                            "deprecatedSupport": .bool(true),
                            "resolveSupport": .object(["properties": .array([.string("documentation"), .string("detail"), .string("additionalTextEdits")])]),
                        ]),
                        "contextSupport": .bool(true),
                    ]),
                    "hover": .object(["contentFormat": .array([.string("markdown"), .string("plaintext")])]),
                    "signatureHelp": .object([
                        "signatureInformation": .object([
                            "documentationFormat": .array([.string("markdown"), .string("plaintext")]),
                            "parameterInformation": .object(["labelOffsetSupport": .bool(true)]),
                            "activeParameterSupport": .bool(true),
                        ]),
                        "contextSupport": .bool(true),
                    ]),
                    "publishDiagnostics": .object(["versionSupport": .bool(true)]),
                ]),
                "window": .object(["workDoneProgress": .bool(false)]),
            ]),
        ])
    }

    static func didOpenParams(uri: String, text: String, version: Int) -> JSONValue {
        .object(["textDocument": .object([
            "uri": .string(uri), "languageId": .string("php"), "version": .number(Double(version)), "text": .string(text),
        ])])
    }

    private func connectionClosed(pid: pid_t) async {
        guard connection?.pid == pid else { return }
        connection = nil
        if stoppedByClient {
            setState(.stopped)
            return
        }
        // Crash: restart with backoff; documents are re-opened from our copy of their text.
        restartAttempts += 1
        guard restartAttempts <= 5 else {
            setState(.failed("PHPantom stopped unexpectedly and could not be restarted. Use Restart Language Server to try again."))
            return
        }
        setState(.restarting(attempt: restartAttempts))
        try? await Task.sleep(for: .milliseconds(300 * restartAttempts))
        await start()
        if state.isReady { restartAttempts = 0 }
    }

    public func stop() async {
        stoppedByClient = true
        guard let connection else {
            setState(.stopped)
            return
        }
        _ = try? await connection.request("shutdown", .null, timeout: .seconds(2))
        connection.notify("exit", .null)
        await connection.terminate()
        self.connection = nil
        setState(.stopped)
    }

    /// Manual restart (clears the crash counter).
    public func restart() async {
        await stop()
        restartAttempts = 0
        await start()
    }

    /// For tests and diagnostics: kill the server process without telling the session.
    public func simulateCrash() {
        connection?.kill()
    }

    public var serverPid: pid_t? { connection?.pid }

    // MARK: Documents

    public func open(uri: String, text: String, version: Int) {
        openDocuments[uri] = (text, version)
        connection?.notify("textDocument/didOpen", Self.didOpenParams(uri: uri, text: text, version: version))
    }

    public func change(uri: String, text: String, version: Int) {
        guard openDocuments[uri] != nil else {
            open(uri: uri, text: text, version: version)
            return
        }
        openDocuments[uri] = (text, version)
        connection?.notify("textDocument/didChange", .object([
            "textDocument": .object(["uri": .string(uri), "version": .number(Double(version))]),
            "contentChanges": .array([.object(["text": .string(text)])]),
        ]))
    }

    public func close(uri: String) {
        guard openDocuments.removeValue(forKey: uri) != nil else { return }
        connection?.notify("textDocument/didClose", .object(["textDocument": .object(["uri": .string(uri)])]))
    }

    public var openDocumentCount: Int { openDocuments.count }

    public func documentVersion(uri: String) -> Int? { openDocuments[uri]?.version }

    private func handleNotification(_ method: String, _ params: JSONValue) {
        guard method == "textDocument/publishDiagnostics", let uri = params["uri"]?.stringValue else { return }
        let diagnostics = (try? params["diagnostics"]?.decode([LSPDiagnostic].self)) ?? []
        let update = DiagnosticsUpdate(uri: uri, version: params["version"]?.intValue, diagnostics: diagnostics)
        diagnosticsContinuations.values.forEach { $0.yield(update) }
    }

    // MARK: Requests (positions are LSP coordinates)

    private func readyConnection() async throws -> LSPConnection {
        if connection == nil || !state.isReady { await start() }
        guard let connection, state.isReady else { throw LSPConnectionClosed() }
        return connection
    }

    private static func positionParams(uri: String, position: LSPPosition) -> [String: JSONValue] {
        ["textDocument": .object(["uri": .string(uri)]), "position": .object(["line": .number(Double(position.line)), "character": .number(Double(position.character))])]
    }

    public func completion(uri: String, position: LSPPosition, triggerCharacter: String?) async throws -> [CompletionItem] {
        let connection = try await readyConnection()
        var params = Self.positionParams(uri: uri, position: position)
        if let triggerCharacter {
            params["context"] = .object(["triggerKind": .number(2), "triggerCharacter": .string(triggerCharacter)])
        } else {
            params["context"] = .object(["triggerKind": .number(1)])
        }
        let result = try await connection.request("textDocument/completion", .object(params), timeout: .seconds(10))
        let items = result["items"]?.arrayValue ?? result.arrayValue ?? []
        return items.enumerated().compactMap { CompletionItem.parse($1, index: $0) }
    }

    public func resolve(_ item: CompletionItem) async throws -> CompletionItem {
        let connection = try await readyConnection()
        let result = try await connection.request("completionItem/resolve", item.raw, timeout: .seconds(5))
        return CompletionItem.parse(result, index: item.id) ?? item
    }

    public func hover(uri: String, position: LSPPosition) async throws -> HoverInfo? {
        let connection = try await readyConnection()
        let result = try await connection.request("textDocument/hover", .object(Self.positionParams(uri: uri, position: position)), timeout: .seconds(5))
        guard let text = markupText(result["contents"]), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        return HoverInfo(markdown: text, range: try? result["range"]?.decode(LSPRange.self))
    }

    public func signatureHelp(uri: String, position: LSPPosition) async throws -> SignatureHelpInfo? {
        let connection = try await readyConnection()
        let result = try await connection.request("textDocument/signatureHelp", .object(Self.positionParams(uri: uri, position: position)), timeout: .seconds(5))
        return SignatureHelpInfo.parse(result)
    }

    public var completionTriggerCharacters: [String] {
        serverCapabilities["completionProvider"]?["triggerCharacters"]?.arrayValue?.compactMap(\.stringValue) ?? ["$", ">", ":", "\\"]
    }

    public var signatureTriggerCharacters: [String] {
        serverCapabilities["signatureHelpProvider"]?["triggerCharacters"]?.arrayValue?.compactMap(\.stringValue) ?? ["(", ","]
    }
}

extension ExecutableLocator {
    /// A small environment for helper processes that must not inherit tool configuration.
    public static func minimalEnvironment() -> [String: String] {
        var environment: [String: String] = [:]
        let inherited = ProcessInfo.processInfo.environment
        for key in ["HOME", "USER", "LOGNAME", "TMPDIR", "LANG", "LC_ALL"] {
            if let value = inherited[key] { environment[key] = value }
        }
        environment["PATH"] = "/usr/bin:/bin"
        if environment["HOME"] == nil { environment["HOME"] = NSHomeDirectory() }
        return environment
    }
}
