import Foundation
@testable import RunletCore
import Testing
@testable import RunletExecution

/// Show Definition (#148) against live MariaDB and PostgreSQL servers, on `p148_` tables (keys,
/// a foreign key, indexes, a check, a trigger, a view, and a PostgreSQL enum and identity), through
/// a project's connection and a saved one. They run only when `RUNLET_TEST_MYSQL` /
/// `RUNLET_TEST_PGSQL` are set (`scripts/setup-fixtures.sh databases`).
@Suite(.serialized, .live(.sql), .enabled(if: TestSupport.hasPHP, "requires host PHP"))
struct SQLDefinitionLiveTests {
    typealias Server = SQLLiveDatabaseTests.Server

    static var servers: [Server] { SQLLiveDatabaseTests.servers }

    /// The `p148_` objects, created again each time.
    static func setup(_ server: Server) throws {
        let statements = server.dialect == "mysql" ? [
            "DROP VIEW IF EXISTS p148_open_orders",
            "DROP TABLE IF EXISTS p148_orders, p148_customers",
            "CREATE TABLE p148_customers (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL, country CHAR(2) DEFAULT 'UK', UNIQUE KEY p148_customers_email (email)) ENGINE=InnoDB",
            "CREATE TABLE p148_orders (id BIGINT AUTO_INCREMENT PRIMARY KEY, customer_id INT NOT NULL, status ENUM('pending','paid','shipped') NOT NULL DEFAULT 'pending', total DECIMAL(10,2) NOT NULL DEFAULT 0, note TEXT, CONSTRAINT p148_orders_customer FOREIGN KEY (customer_id) REFERENCES p148_customers(id) ON DELETE CASCADE, CONSTRAINT p148_orders_total CHECK (total >= 0), KEY p148_orders_status (status, customer_id)) ENGINE=InnoDB COMMENT='Orders placed by customers'",
            "CREATE TRIGGER p148_orders_touch BEFORE UPDATE ON p148_orders FOR EACH ROW SET NEW.total = GREATEST(NEW.total, 0)",
            "CREATE VIEW p148_open_orders AS SELECT o.id, c.email, o.total FROM p148_orders o JOIN p148_customers c ON c.id = o.customer_id WHERE o.status <> 'shipped'",
            "INSERT INTO p148_customers (email) VALUES ('a@example.test')",
        ] : [
            "DROP VIEW IF EXISTS p148_open_orders",
            "DROP TABLE IF EXISTS p148_orders, p148_customers",
            "DROP TYPE IF EXISTS p148_status",
            "CREATE TYPE p148_status AS ENUM ('pending', 'paid', 'shipped')",
            "CREATE TABLE p148_customers (id SERIAL PRIMARY KEY, email VARCHAR(190) NOT NULL, country CHAR(2) DEFAULT 'UK', CONSTRAINT p148_customers_email UNIQUE (email))",
            "CREATE TABLE p148_orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id INT NOT NULL REFERENCES p148_customers(id) ON DELETE CASCADE, status p148_status NOT NULL DEFAULT 'pending', total NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0), note TEXT COLLATE \"C\", placed_at TIMESTAMPTZ NOT NULL DEFAULT now())",
            "CREATE INDEX p148_orders_status ON p148_orders (status, customer_id)",
            "CREATE UNIQUE INDEX p148_orders_note ON p148_orders (lower(note)) WHERE note IS NOT NULL",
            "COMMENT ON TABLE p148_orders IS 'Orders placed by customers'",
            "COMMENT ON COLUMN p148_orders.total IS 'In euros'",
            "CREATE VIEW p148_open_orders AS SELECT o.id, c.email, o.total FROM p148_orders o JOIN p148_customers c ON c.id = o.customer_id WHERE o.status <> 'shipped'",
            "INSERT INTO p148_customers (email) VALUES ('a@example.test')",
        ]
        for statement in statements { _ = try server.exec(statement) }
    }

    static func load(_ server: Server, _ table: String) async throws -> SQLDefinitionInfo {
        let directory = try server.project()
        defer { try? FileManager.default.removeItem(at: directory) }
        return try await ExecutionEngine(bundle: TestSupport.bundle, docker: nil).loadSQLDefinition(target: DriverSupport.target(directory.path), table: table, connection: nil)
    }

    @Test(.enabled(if: SQLLiveDatabaseTests.mysql != nil, "set RUNLET_TEST_MYSQL"))
    func mariadbShowCreate() async throws {
        let server = try #require(SQLLiveDatabaseTests.mysql)
        try Self.setup(server)
        let orders = try await Self.load(server, "p148_orders")
        #expect(orders.kind == "table" && orders.how == "SHOW CREATE TABLE" && orders.driver == "mysql")
        #expect(orders.reconstructed == nil && orders.notes == nil, "\(orders.notes ?? [])")
        #expect(orders.server?.hasPrefix("MariaDB ") == true || orders.server?.hasPrefix("MySQL ") == true, "\(orders.server ?? "-")")
        let statements = orders.sql.components(separatedBy: "\n\n")
        #expect(statements.count == 2, "\(orders.sql)")
        for part in ["CREATE TABLE `p148_orders` (", "PRIMARY KEY (`id`)", "KEY `p148_orders_status` (`status`,`customer_id`)",
                     "CONSTRAINT `p148_orders_customer` FOREIGN KEY (`customer_id`) REFERENCES `p148_customers` (`id`) ON DELETE CASCADE",
                     "CONSTRAINT `p148_orders_total` CHECK (`total` >= 0)", "ENGINE=InnoDB", "COMMENT='Orders placed by customers';"] {
            #expect(statements[0].contains(part), "\(part) in \(statements[0])")
        }
        #expect(statements[1].contains("TRIGGER p148_orders_touch BEFORE UPDATE ON p148_orders FOR EACH ROW"), "\(statements[1])")
        #expect(statements[1].hasSuffix(";"))

        let view = try await Self.load(server, "p148_open_orders")
        #expect(view.kind == "view" && view.how == "SHOW CREATE VIEW")
        #expect(view.sql.contains("VIEW `p148_open_orders` AS select"), "\(view.sql)")
        #expect(!view.sql.contains("\n\n"), "a view has no triggers")
        #expect(try server.exec("SELECT COUNT(*) FROM p148_customers") == "1", "nothing ran but the catalog read")
    }

    @Test(.enabled(if: SQLLiveDatabaseTests.pgsql != nil, "set RUNLET_TEST_PGSQL"))
    func postgresReconstructed() async throws {
        let server = try #require(SQLLiveDatabaseTests.pgsql)
        try Self.setup(server)
        let orders = try await Self.load(server, "p148_orders")
        #expect(orders.kind == "table" && orders.how == "pg_catalog" && orders.reconstructed == true)
        #expect(orders.server?.hasPrefix("PostgreSQL ") == true)
        #expect(orders.notes == ["Reconstructed by Runlet from the catalog: PostgreSQL has no SHOW CREATE TABLE.", "Left out: owner, privileges, policies, rules, and the sequences behind serial columns."])
        // The same text the recorded rows give (SQLDefinitionTests), but for the placed_at column the recording left out.
        #expect(orders.sql.contains("CREATE TYPE p148_status AS ENUM ('pending', 'paid', 'shipped');"))
        for line in ["    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,", "    status p148_status DEFAULT 'pending'::p148_status NOT NULL,",
                     "    note text COLLATE pg_catalog.\"C\",", "    placed_at timestamp with time zone DEFAULT now() NOT NULL,",
                     "    CONSTRAINT p148_orders_pkey PRIMARY KEY (id),", "    CONSTRAINT p148_orders_total_check CHECK (total >= 0::numeric),",
                     "    CONSTRAINT p148_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES p148_customers(id) ON DELETE CASCADE",
                     "CREATE UNIQUE INDEX p148_orders_note ON public.p148_orders USING btree (lower(note)) WHERE (note IS NOT NULL);",
                     "CREATE INDEX p148_orders_status ON public.p148_orders USING btree (status, customer_id);",
                     "COMMENT ON TABLE public.p148_orders IS 'Orders placed by customers';", "COMMENT ON COLUMN public.p148_orders.total IS 'In euros';"] {
            #expect(orders.sql.components(separatedBy: "\n").contains(line), "\(line) in \(orders.sql)")
        }
        #expect(!orders.sql.contains("p148_orders_pkey ON"), "a constraint's own index isn't repeated")

        let customers = try await Self.load(server, "p148_customers")
        #expect(customers.sql.contains("    id integer DEFAULT nextval('p148_customers_id_seq'::regclass) NOT NULL,"), "\(customers.sql)")
        #expect(customers.sql.contains("    CONSTRAINT p148_customers_email UNIQUE (email)"))
        #expect(!customers.sql.contains("CREATE TYPE"))

        let view = try await Self.load(server, "p148_open_orders")
        #expect(view.kind == "view")
        #expect(view.sql.hasPrefix("CREATE OR REPLACE VIEW public.p148_open_orders AS\nSELECT o.id,"), "\(view.sql)")
        #expect(view.sql.hasSuffix("WHERE o.status <> 'shipped'::p148_status;"), "\(view.sql)")
        #expect(try server.exec("SELECT COUNT(*) FROM p148_customers") == "1", "nothing ran but the catalog read")
    }

    /// #142: an all-targets connection opened from this Mac (`LocalConnectionLaunch`).
    @Test(.enabled(if: !servers.isEmpty, "set RUNLET_TEST_MYSQL or RUNLET_TEST_PGSQL"))
    func fromThisMac() async throws {
        for server in Self.servers {
            try Self.setup(server)
            for php in SQLLiveFromThisMacTests.phps {
                let (connection, store) = SQLLiveFromThisMacTests.connection(server, readOnly: true)
                let place = try SQLLiveFromThisMacTests.place(connection, store: store, php: php)
                defer { try? FileManager.default.removeItem(at: place.root) }
                let info = try await place.engine.loadSQLDefinition(target: place.target, table: "p148_orders", connection: nil, saved: connection)
                #expect(info.saved == true && info.connection == "Analytics", "\(server.dialect) via \(php.label)")
                #expect(info.how == (server.dialect == "pgsql" ? "pg_catalog" : "SHOW CREATE TABLE"), "\(server.dialect) via \(php.label)")
                #expect(info.sql.contains("p148_orders_status"), "\(server.dialect) via \(php.label): \(info.sql)")
            }
        }
    }

    @Test(.enabled(if: !servers.isEmpty, "set RUNLET_TEST_MYSQL or RUNLET_TEST_PGSQL"))
    func savedReadOnlyConnections() async throws {
        for server in Self.servers {
            try Self.setup(server)
            let (saved, store) = SQLLiveDatabaseTests.saved(server)
            var connection = saved
            connection.readOnly = true
            let directory = try SQLSavedConnectionTests.project()
            defer { try? FileManager.default.removeItem(at: directory) }
            let engine = ExecutionEngine(bundle: TestSupport.bundle, docker: nil, credentials: store)
            let info = try await engine.loadSQLDefinition(target: DriverSupport.target(directory.path), table: "p148_orders", connection: nil, saved: connection)
            #expect(info.saved == true && info.connection == "Reporting replica", "\(server.dialect)")
            #expect(info.sql.contains("p148_orders_status"), "\(server.dialect): \(info.sql)")
            #expect(SQLSavedConnectionTests.markers(in: directory).isEmpty, "\(server.dialect): no project code ran")
            #expect(!String(reflecting: info).contains(server.password), "\(server.dialect)")
            await #expect(throws: SQLDefinitionLoadError.self, "\(server.dialect)") {
                try await engine.loadSQLDefinition(target: DriverSupport.target(directory.path), table: "p148_missing", connection: nil, saved: connection)
            }
        }
    }
}
