import Foundation
@testable import RunletCore
import Testing
@testable import RunletExecution

/// Browse Table (#151) against live MariaDB 11 and PostgreSQL 14 (the fixture containers of
/// `scripts/setup-fixtures.sh databases`, through `RUNLET_TEST_MYSQL` / `RUNLET_TEST_PGSQL`):
/// pages, sort, and filters on the server with the schema's real column types; edits, an
/// insertion, and a deletion applied in one transaction (MariaDB's UPDATE that changes nothing
/// is told from a missing row by its count); a rollback when another session changed a row in
/// the meantime; and a read-only saved connection that never applies. The tests use their own
/// `p151_items` table, created on each run.
@Suite(.serialized, .live(.sql), .enabled(if: TestSupport.hasPHP, "requires host PHP"))
struct SQLTableBrowseLiveTests {
    typealias Server = SQLLiveDatabaseTests.Server

    /// `p151_items`: 120 rows, `id` 1…120, `name` "Widget 001"…, `price` id / 4, `active` for even
    /// ids, `note` NULL for every tenth row.
    static func setup(_ server: Server) throws {
        _ = try server.exec("DROP TABLE IF EXISTS p151_items")
        if server.dialect == "mysql" {
            _ = try server.exec("CREATE TABLE p151_items (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(40) NOT NULL, price DECIMAL(8,2), active TINYINT(1) NOT NULL DEFAULT 0, note TEXT) ENGINE=InnoDB")
            _ = try server.exec("INSERT INTO p151_items (id, name, price, active, note) SELECT seq, CONCAT('Widget ', LPAD(seq, 3, '0')), seq / 4, seq % 2 = 0, IF(seq % 10 = 0, NULL, CONCAT('note ', seq)) FROM seq_1_to_120")
        } else {
            _ = try server.exec("CREATE TABLE p151_items (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(40) NOT NULL, price NUMERIC(8,2), active BOOLEAN NOT NULL DEFAULT false, note TEXT)")
            _ = try server.exec("INSERT INTO p151_items (id, name, price, active, note) SELECT i, 'Widget ' || LPAD(i::text, 3, '0'), i / 4.0, i % 2 = 0, CASE WHEN i % 10 = 0 THEN NULL ELSE 'note ' || i END FROM generate_series(1, 120) AS i")
            _ = try server.exec("SELECT setval(pg_get_serial_sequence('p151_items', 'id'), 120)")
        }
        #expect(try server.exec("SELECT COUNT(*) FROM p151_items") == "120")
    }

    /// The table as the schema explorer has it: read through the runner, as Load Schema does.
    func table(_ server: Server, in directory: URL) async throws -> SQLSchemaInfo.Table {
        let events = try await TestSupport.run(SQLTabRun.schemaCode(connection: nil), target: DriverSupport.target(directory.path), magicComments: false)
        #expect(events.errors.isEmpty, "\(server.dialect): \(events.errors)")
        let schema = try #require(events.sqlSchema)
        #expect(schema.driver == server.dialect)
        return try #require(schema.table(named: "p151_items"))
    }

    func request(_ table: SQLSchemaInfo.Table, _ server: Server, sort: SQLTableBrowse.Sort? = nil, filters: [SQLTableBrowse.Filter] = [], offset: Int = 0, pageSize: Int = 50) throws -> SQLTableBrowse.Request {
        let dialect = try #require(SQLTableBrowse.Dialect(driver: server.dialect))
        return SQLTableBrowse.Request(table: table.name, columns: table.columns, dialect: dialect, sort: sort, filters: filters, offset: offset, pageSize: pageSize)
    }

    func page(_ request: SQLTableBrowse.Request, _ server: Server, saved: DatabaseConnection? = nil, in directory: URL) async throws -> SQLResultInfo {
        let code = SQLTabRun.browseCode(try SQLTableBrowse.query(request).get(), connection: nil, driver: server.dialect)
        let events = saved == nil
            ? try await TestSupport.run(code, target: DriverSupport.target(directory.path), magicComments: false)
            : try await SQLSavedConnectionTests.run(code, connection: saved!, in: directory, password: server.password)
        #expect(events.errors.isEmpty, "\(server.dialect): \(events.errors)")
        return try #require(events.sqlResult)
    }

    func apply(_ statements: [SQLTableEdits.Statement], _ server: Server, saved: DatabaseConnection? = nil, in directory: URL) async throws -> [RunEvent] {
        let code = SQLTabRun.applyCode(statements, connection: nil, driver: server.dialect)
        if let saved { return try await SQLSavedConnectionTests.run(code, connection: saved, in: directory, password: server.password) }
        return try await TestSupport.run(code, target: DriverSupport.target(directory.path), magicComments: false)
    }

    func statements(_ changes: SQLTableEdits.Changes, table: SQLSchemaInfo.Table, page: SQLResultInfo, _ server: Server) throws -> [SQLTableEdits.Statement] {
        try SQLTableEdits.statements(changes, table: table.name, columns: table.columns, rows: page.rows, dialect: #require(SQLTableBrowse.Dialect(driver: server.dialect))).get()
    }

    @Test(.enabled(if: !SQLLiveDatabaseTests.servers.isEmpty, "set RUNLET_TEST_MYSQL or RUNLET_TEST_PGSQL"))
    func pagesSortAndFiltersRunOnTheServer() async throws {
        for server in SQLLiveDatabaseTests.servers {
            try Self.setup(server)
            let directory = try server.project()
            defer { try? FileManager.default.removeItem(at: directory) }
            let table = try await table(server, in: directory)
            #expect(table.columns.first { $0.primaryKey == true }?.name == "id")
            #expect(SQLTableEdits.refusal(table: table, driver: server.dialect, source: nil, readOnlyConnection: nil) == nil, "\(server.dialect): editable")
            let first = try await page(request(table, server), server, in: directory)
            #expect(first.columns == ["id", "name", "price", "active", "note"], "\(server.dialect)")
            #expect(first.rows.count == 50)
            #expect(first.truncated == true)
            let last = try await page(request(table, server, offset: 100), server, in: directory)
            #expect(last.rows.map { $0[0].text } == (101...120).map(String.init), "\(server.dialect)")
            #expect(last.truncated == nil)
            let sorted = try await page(request(table, server, sort: .init(column: "price", ascending: false), pageSize: 2), server, in: directory)
            #expect(sorted.rows.map { $0[0].text } == ["120", "119"], "\(server.dialect)")
            // "contains" ignores case (ILIKE on PostgreSQL); values are typed and bound.
            let filtered = try await page(request(table, server, filters: [
                .init(column: "name", op: .contains, value: "WIDGET 0"),
                .init(column: "price", op: .greaterThan, value: "20"),
                .init(column: "note", op: .isEmpty),
                .init(column: "active", op: .equals, value: server.dialect == "mysql" ? "1" : "true"),
            ]), server, in: directory)
            #expect(filtered.rows.map { $0[0].text } == ["90"], "\(server.dialect): \(filtered.rows)")
            let injected = try await page(request(table, server, filters: [.init(column: "name", op: .equals, value: "x' OR '1'='1")]), server, in: directory)
            #expect(injected.rows.isEmpty, "\(server.dialect)")
        }
    }

    @Test(.enabled(if: !SQLLiveDatabaseTests.servers.isEmpty, "set RUNLET_TEST_MYSQL or RUNLET_TEST_PGSQL"))
    func editsInsertsAndDeletesApplyInOneTransaction() async throws {
        for server in SQLLiveDatabaseTests.servers {
            try Self.setup(server)
            let directory = try server.project()
            defer { try? FileManager.default.removeItem(at: directory) }
            let table = try await table(server, in: directory)
            let first = try await page(request(table, server, pageSize: 10), server, in: directory)
            var changes = SQLTableEdits.Changes()
            changes.set(row: 0, column: 1, to: .text("Lamp"), original: first.rows[0][1])
            changes.set(row: 0, column: 4, to: .null, original: first.rows[0][4])
            // 0.50 → "0.5": the same number. MariaDB reports no changed row; the count tells.
            changes.set(row: 1, column: 2, to: .text("0.5"), original: first.rows[1][2])
            changes.delete(rows: [2])
            changes.addRow()
            changes.setNew(row: 0, column: 1, to: .text("Chair"))
            changes.setNew(row: 0, column: 2, to: .text("45.50"))
            let all = try statements(changes, table: table, page: first, server)
            #expect(all.map(\.kind) == [.delete, .update, .update, .insert])
            #expect(all[1].verifySQL != nil || server.dialect == "pgsql")
            let events = try await apply(all, server, in: directory)
            #expect(events.errors.isEmpty, "\(server.dialect): \(events.errors)")
            #expect(events.sqlResults.map(\.affectedRows) == [1, 1, 1, 1], "\(server.dialect)")
            #expect(events.sqlNotices.last == "Committed the transaction: all 4 changes affected exactly one row each.")
            #expect(try server.exec("SELECT COUNT(*) FROM p151_items") == "120")
            #expect(try server.exec("SELECT name FROM p151_items WHERE id = 1") == "Lamp")
            #expect(try server.exec("SELECT COUNT(*) FROM p151_items WHERE id = 1 AND note IS NULL") == "1")
            #expect(try server.exec("SELECT COUNT(*) FROM p151_items WHERE id = 3") == "0")
            #expect(try server.exec("SELECT price FROM p151_items WHERE name = 'Chair'") == "45.50", "\(server.dialect)")
            #expect(try server.exec("SELECT id FROM p151_items WHERE name = 'Chair'") == "121", "\(server.dialect): the key's default")
        }
    }

    @Test(.enabled(if: !SQLLiveDatabaseTests.servers.isEmpty, "set RUNLET_TEST_MYSQL or RUNLET_TEST_PGSQL"))
    func aRowChangedByAnotherSessionRollsBack() async throws {
        for server in SQLLiveDatabaseTests.servers {
            try Self.setup(server)
            let directory = try server.project()
            defer { try? FileManager.default.removeItem(at: directory) }
            let table = try await table(server, in: directory)
            let first = try await page(request(table, server, pageSize: 10), server, in: directory)
            var changes = SQLTableEdits.Changes()
            changes.delete(rows: [4])
            changes.set(row: 0, column: 2, to: .text("9.99"), original: first.rows[0][2])
            // Another session changes the price after the page was read.
            _ = try server.exec("UPDATE p151_items SET price = 1.00 WHERE id = 1")
            let events = try await apply(try statements(changes, table: table, page: first, server), server, in: directory)
            let error = try #require(events.errors.first, "\(server.dialect)")
            #expect(error.className == "RunletRunner\\SqlEditsFailed")
            #expect(error.message.hasPrefix("Change 2 of 2 (row 1 · id = 1): row not found: it was changed or deleted by someone else since the page was read"), "\(server.dialect): \(error.message)")
            #expect(error.message.hasSuffix("Rolled back the transaction: nothing was changed."))
            #expect(try server.exec("SELECT COUNT(*) FROM p151_items WHERE id = 5") == "1", "\(server.dialect): the DELETE was rolled back")
            #expect(try server.exec("SELECT price FROM p151_items WHERE id = 1") == "1.00")
            // A row another session deleted isn't found either.
            _ = try server.exec("DELETE FROM p151_items WHERE id = 7")
            var gone = SQLTableEdits.Changes()
            gone.set(row: 6, column: 1, to: .text("Gone"), original: first.rows[6][1])
            let missing = try await apply(try statements(gone, table: table, page: first, server), server, in: directory)
            #expect(missing.errors.first?.message.hasPrefix("Change 1 of 1 (row 7 · id = 7): row not found") == true, "\(server.dialect): \(missing.errors)")
        }
    }

    @Test(.enabled(if: !SQLLiveDatabaseTests.servers.isEmpty, "set RUNLET_TEST_MYSQL or RUNLET_TEST_PGSQL"))
    func readOnlySavedConnectionsBrowseButNeverApply() async throws {
        for server in SQLLiveDatabaseTests.servers {
            try Self.setup(server)
            let directory = try SQLSavedConnectionTests.project()
            defer { try? FileManager.default.removeItem(at: directory) }
            let project = try server.project()
            defer { try? FileManager.default.removeItem(at: project) }
            let table = try await table(server, in: project)
            var (connection, _) = SQLLiveDatabaseTests.saved(server)
            connection.readOnly = true
            #expect(SQLTableEdits.refusal(table: table, driver: server.dialect, source: nil, readOnlyConnection: connection.name) == .readOnlyConnection(connection.name))
            let first = try await page(request(table, server, pageSize: 5), server, saved: connection, in: directory)
            #expect(first.rows.count == 5, "\(server.dialect)")
            #expect(first.saved == true)
            // Should a change reach the runner, the read-only connection refuses it before connecting.
            var changes = SQLTableEdits.Changes()
            changes.delete(rows: [0])
            let refused = try await apply(try statements(changes, table: table, page: first, server), server, saved: connection, in: directory)
            #expect(refused.errors.first?.className == "RunletRunner\\SqlReadOnlyRefused", "\(server.dialect): \(refused.errors)")
            #expect(try server.exec("SELECT COUNT(*) FROM p151_items") == "120")
        }
    }
}
