import Foundation
import RunletCore
@testable import RunletExecution

enum TestSupport {
    static let repoRoot: URL = {
        var url = URL(fileURLWithPath: #filePath)
        while url.path != "/" {
            url.deleteLastPathComponent()
            if FileManager.default.fileExists(atPath: url.appendingPathComponent("plan.md").path) { return url }
        }
        fatalError("repository root not found")
    }()

    static var bundle: RunnerBundle {
        try! RunnerBundle(contentsOf: repoRoot.appendingPathComponent("Resources/Runner/dist/runlet-runner.php"))
    }

    static var fixtures: URL { repoRoot.appendingPathComponent("Tests/Fixtures") }

    /// `Tests/Fixtures/wordpress`, generated by `scripts/setup-fixtures.sh`.
    static var hasWordPressFixture: Bool {
        FileManager.default.fileExists(atPath: fixtures.appendingPathComponent("wordpress/.runlet-fixture-ready").path)
    }

    /// The WordPress fixture, for a test that runs it or changes it: the test needs
    /// `.fixture(.wordpress)` (#242), since tests add must-use plugins to it.
    static var wordpressFixture: URL {
        Fixtures.use(.wordpress)
        return fixtures.appendingPathComponent("wordpress")
    }

    /// Clones the WordPress fixture to `directory` (APFS copies it without copying the bytes),
    /// without the must-use plugins (`runlet-test-*.php`) that a test running at the same time
    /// may have added (#242). A copy needs no `.fixture(.wordpress)`.
    static func cloneWordPressFixture(to directory: URL) throws {
        try FileManager.default.copyItem(at: fixtures.appendingPathComponent("wordpress"), to: directory)
        let muPlugins = directory.appendingPathComponent("wp-content/mu-plugins")
        for name in (try? FileManager.default.contentsOfDirectory(atPath: muPlugins.path)) ?? [] where name.hasPrefix("runlet-test-") {
            try FileManager.default.removeItem(at: muPlugins.appendingPathComponent(name))
        }
    }

    static func php(_ name: String = "php") -> String? {
        ExecutableLocator.resolve(name)
    }

    static var herdPHP74: String? {
        ExecutableLocator.resolve("\(NSHomeDirectory())/Library/Application Support/Herd/bin/php74")
    }

    /// Herd's PHP 7.4 to 8.2 that exist on this Mac: the versions that define no STDIN/STDOUT/STDERR
    /// for a script read from stdin, as Runlet sends its runner (#351). Empty without Herd.
    static var herdOlderPHPs: [String] {
        ["php74", "php80", "php81", "php82"].compactMap {
            ExecutableLocator.resolve("\(NSHomeDirectory())/Library/Application Support/Herd/bin/\($0)")
        }
    }

    /// `Tests/Fixtures/docker/fixtures-only-docker`: the real Docker CLI limited to Runlet's
    /// disposable containers (the `runlet-fixtures` Compose projects and Runlet's sandbox).
    static var fixturesOnlyDockerScript: URL { fixtures.appendingPathComponent("docker/fixtures-only-docker") }

    /// The real Docker CLI: `RUNLET_REAL_DOCKER` when set, else `docker` on PATH or in the usual
    /// install folders (`ExecutableLocator`, as the app finds it), skipping the wrapper itself
    /// (older docs had a `docker` symlink to it first on PATH).
    static var realDockerExecutable: String? {
        if let explicit = ProcessInfo.processInfo.environment["RUNLET_REAL_DOCKER"], !explicit.isEmpty {
            return ExecutableLocator.resolve(explicit)
        }
        let wrapper = fixturesOnlyDockerScript.resolvingSymlinksInPath().path
        return ExecutableLocator.searchPath
            .map { URL(fileURLWithPath: $0).appendingPathComponent("docker") }
            .first { ExecutableLocator.isExecutable($0.path) && $0.resolvingSymlinksInPath().path != wrapper }?
            .path
    }

    /// A Docker CLI that runs `real` only through the fixtures-only wrapper: its executable is a
    /// `docker` launcher in a fresh temporary folder that hands `real` to the wrapper
    /// (`RUNLET_REAL_DOCKER`). Callers that run `executable` themselves (a terminal, a
    /// `Process`, a wrapping script) stay inside the wrapper too, and so does anything that
    /// looks `docker` up on the CLI's PATH, where the launcher's folder comes first.
    static func fixturesOnlyDocker(wrapping real: String) throws -> DockerCLI {
        let folder = FileManager.default.temporaryDirectory.appendingPathComponent("runlet-fixtures-docker-\(UUID().uuidString.prefix(8))", isDirectory: true)
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let launcher = folder.appendingPathComponent("docker")
        try """
        #!/bin/sh
        # Generated by the RunletKit tests (#80): Docker limited to Runlet's disposable containers.
        RUNLET_REAL_DOCKER=\(RemoteShell.quote(real))
        export RUNLET_REAL_DOCKER
        exec \(RemoteShell.quote(fixturesOnlyDockerScript.path)) "$@"

        """.write(to: launcher, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: launcher.path)
        return DockerCLI(executable: launcher.path)
    }

    /// The Docker CLI of every test that runs Docker, always through the fixtures-only wrapper
    /// (#80): tests see only the `runlet-fixtures` containers and Runlet's own sandbox
    /// containers, never the developer's other containers. nil without a responding Docker.
    /// Using it counts as using the Docker fixture: the test needs `.live(.docker)` (#242).
    static var docker: DockerCLI? {
        Fixtures.use(.docker)
        return dockerCLI
    }

    /// `docker`, unchecked: for engines that get a Docker CLI but run on this Mac.
    private static let dockerCLI: DockerCLI? = {
        guard let real = realDockerExecutable, let cli = try? fixturesOnlyDocker(wrapping: real) else { return nil }
        // `docker version` (what `DockerCLI.serverVersion()` runs), waited for on the process's
        // termination handler rather than a semaphore on a Swift-concurrency thread: parallel
        // tests that reach this at once must not need a free cooperative thread (#242).
        let check = try? TestProcess.runBlocking([cli.executable, "version", "--format", "{{.Server.Version}}"], step: "docker version", within: .seconds(10), environment: cli.environment)
        guard let check, check.status == 0, !check.output.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        return cli
    }()

    static var hasPHP: Bool { php() != nil }
    static var hasDocker: Bool { docker != nil }

    static func localTarget(_ directory: String, php: String) -> TargetSnapshot {
        TargetSnapshot(kind: .local, label: "test", targetId: "test", workingDirectory: directory, phpExecutable: php)
    }

    static func run(_ code: String, target: TargetSnapshot, engine: ExecutionEngine? = nil, selection: SourceSelection? = nil, strictTypes: Bool = false, inspector: RunInspectorOptions = RunInspectorOptions(), magicComments: Bool = true) async throws -> [RunEvent] {
        let engine = engine ?? ExecutionEngine(bundle: bundle, docker: dockerCLI)
        let request = RunRequest(tabId: UUID(), documentVersion: 1, target: target, code: code, selection: selection, strictTypes: strictTypes, inspector: inspector, magicComments: magicComments)
        var events: [RunEvent] = []
        for await event in try await engine.start(request) { events.append(event) }
        return events
    }
}

extension Array where Element == RunEvent {
    var finished: FinishedInfo? {
        for event in self { if case .finished(let info) = event.kind { return info } }
        return nil
    }

    var result: ResultInfo? {
        for event in self { if case .result(let info) = event.kind { return info } }
        return nil
    }

    var errors: [RunErrorInfo] {
        compactMap { if case .error(let info) = $0.kind { return info } else { return nil } }
    }

    var dumps: [DumpInfo] {
        compactMap { if case .dump(let info) = $0.kind { return info } else { return nil } }
    }

    var stdout: String {
        String(decoding: compactMap { if case .stdout(let data) = $0.kind { return data } else { return nil } }.reduce(Data(), +), as: UTF8.self)
    }

    var stderr: String {
        String(decoding: compactMap { if case .stderr(let data) = $0.kind { return data } else { return nil } }.reduce(Data(), +), as: UTF8.self)
    }

    var started: StartedInfo? {
        for event in self { if case .started(let info) = event.kind { return info } }
        return nil
    }

    var bootstrapped: BootstrappedInfo? {
        for event in self { if case .bootstrapped(let info) = event.kind { return info } }
        return nil
    }

    /// The run inspector's events, folded the way the app shows them.
    var inspection: RunInspection {
        var inspection = RunInspection()
        for event in self { if case .inspector(let inspectorEvent) = event.kind { inspection.apply(inspectorEvent) } }
        return inspection
    }

    var inspectorInfo: InspectorInfo? {
        for event in self { if case .inspector(.ready(let info)) = event.kind { return info } }
        return nil
    }
}
