<?php

declare(strict_types=1);

/*
 * Builds Resources/Runner/dist/runlet-runner.php: a single self-contained PHP file
 * holding the Runlet runner plus a namespace-scoped copy of nikic/php-parser
 * (PhpParser\ -> RunletVendor\PhpParser\), so the runner never collides with a
 * project's own parser version and never needs Composer inside the user's project.
 *
 * Run with any PHP >= 8.0 (the output itself runs on PHP 7.4+):
 *     php scripts/build-runner.php
 */

const PREFIX = 'RunletVendor';

$root = dirname(__DIR__);
$runnerDir = $root . '/Resources/Runner';
$parserLib = $runnerDir . '/build/vendor/nikic/php-parser/lib/PhpParser';
$outFile = $runnerDir . '/dist/runlet-runner.php';

if (!is_dir($parserLib)) {
    fwrite(STDERR, "php-parser is not installed. Run: composer install --working-dir=Resources/Runner\n");
    exit(1);
}

// Parts of php-parser the runner never uses at runtime.
$excludedPrefixes = ['Builder/', 'PrettyPrinter/', 'NodeVisitor/NameResolver.php', 'NodeVisitor/ParentConnectingVisitor.php', 'NodeVisitor/NodeConnectingVisitor.php', 'NodeVisitor/FindingVisitor.php', 'NodeVisitor/FirstFindingVisitor.php', 'NodeVisitor/CloningVisitor.php'];
$excludedFiles = ['Builder.php', 'BuilderFactory.php', 'BuilderHelpers.php', 'PrettyPrinter.php', 'PrettyPrinterAbstract.php', 'JsonDecoder.php', 'NodeDumper.php', 'ConstExprEvaluator.php', 'ConstExprEvaluationException.php', 'NodeFinder.php', 'compatibility_tokens.php'];
// Deprecated class_alias shims (v4 names); the v5 parser never produces them.
$aliasShims = [];

$files = [];
$iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($parserLib, FilesystemIterator::SKIP_DOTS));
foreach ($iterator as $file) {
    $relative = substr($file->getPathname(), strlen($parserLib) + 1);
    if (substr($relative, -4) !== '.php') {
        continue;
    }
    if (in_array($relative, $excludedFiles, true)) {
        continue;
    }
    foreach ($excludedPrefixes as $prefix) {
        if (strpos($relative, $prefix) === 0) {
            continue 2;
        }
    }
    $contents = file_get_contents($file->getPathname());
    if (strpos($contents, 'if (false) {') !== false && strpos($contents, "require __DIR__") !== false) {
        $aliasShims[] = $relative;
        continue;
    }
    $files[$relative] = $file->getPathname();
}
ksort($files);

// Topologically order class files by recording when each finishes loading:
// a parent class/interface always finishes before its children.
$order = [];
$classToFile = [];
foreach ($files as $relative => $path) {
    $class = 'PhpParser\\' . str_replace('/', '\\', substr($relative, 0, -4));
    $classToFile[$class] = $path;
}
require $parserLib . '/compatibility_tokens.php';
spl_autoload_register(static function (string $class) use (&$order, $classToFile): void {
    if (isset($classToFile[$class])) {
        require $classToFile[$class];
        $order[] = $classToFile[$class];
    }
});
foreach (array_keys($classToFile) as $class) {
    if (!class_exists($class) && !interface_exists($class) && !trait_exists($class) && !(function_exists('enum_exists') && enum_exists($class))) {
        fwrite(STDERR, "Could not load {$class}\n");
        exit(1);
    }
}
$order = array_values(array_unique($order));
if (count($order) !== count($files)) {
    fwrite(STDERR, 'Ordered ' . count($order) . ' files but expected ' . count($files) . "\n");
    exit(1);
}

$out = "<?php\n\ndeclare(strict_types=1);\n\n";
$out .= "// Generated by scripts/build-runner.php. Do not edit; edit Resources/Runner/src instead.\n";
$out .= '// Bundles nikic/php-parser ' . parserVersion($runnerDir) . " (BSD-3-Clause) scoped under " . PREFIX . "\\PhpParser.\n\n";
$out .= scopeFile(file_get_contents($parserLib . '/compatibility_tokens.php'), true);
foreach ($order as $path) {
    $out .= scopeFile(file_get_contents($path), true);
}
// The driver API first (project drivers extend it): the run inspector and its database
// hooks (Runlet\Inspector, Runlet\InspectsDatabases), then Runlet\Driver and Runlet\Drivers\*.
$out .= scopeFile(file_get_contents($runnerDir . '/src/Inspector.php'), false);
$out .= scopeFile(file_get_contents($runnerDir . '/src/Drivers.php'), false);
// Runlet\bench() and the Profile Run profiler (#41), then the runner itself.
$out .= scopeFile(file_get_contents($runnerDir . '/src/Benchmark.php'), false);
$out .= scopeFile(file_get_contents($runnerDir . '/src/Profiler.php'), false);
$out .= scopeFile(file_get_contents($runnerDir . '/src/Runner.php'), false);
// Magic comments (#10): the compiler's probe planner and the Probe runtime.
$out .= scopeFile(file_get_contents($runnerDir . '/src/MagicComments.php'), false);

if (!is_dir(dirname($outFile))) {
    mkdir(dirname($outFile), 0755, true);
}
file_put_contents($outFile, $out);
fwrite(STDOUT, sprintf("Wrote %s (%d bytes, %d parser files, %d alias shims skipped)\n", $outFile, strlen($out), count($order), count($aliasShims)));

function parserVersion(string $runnerDir): string
{
    $installed = json_decode((string) file_get_contents($runnerDir . '/build/vendor/composer/installed.json'), true);
    foreach ($installed['packages'] ?? $installed as $package) {
        if (($package['name'] ?? '') === 'nikic/php-parser') {
            return $package['version'];
        }
    }

    return 'unknown';
}

/**
 * Converts one file into a braced-namespace block and optionally prefixes PhpParser names.
 */
function scopeFile(string $source, bool $scope): string
{
    $source = rewriteEarlyReturn($source);
    $tokens = token_get_all($source);
    $result = '';
    $namespace = null;
    $count = count($tokens);
    $skipDeclare = false;

    for ($i = 0; $i < $count; $i++) {
        $token = $tokens[$i];
        if (!is_array($token)) {
            if ($skipDeclare) {
                if ($token === ';') {
                    $skipDeclare = false;
                }
                continue;
            }
            $result .= $token;
            continue;
        }
        [$id, $text] = $token;

        if ($skipDeclare) {
            continue;
        }
        if ($id === T_OPEN_TAG) {
            continue;
        }
        if ($id === T_DECLARE) {
            $skipDeclare = true;
            continue;
        }
        if ($id === T_REQUIRE && $scope) {
            // Only `require __DIR__ . '/compatibility_tokens.php';` in Lexer.php; inlined already.
            while ($i < $count && $tokens[$i] !== ';') {
                $i++;
            }
            continue;
        }
        if ($id === T_NAMESPACE) {
            // Collect the namespace name up to ';'.
            $name = '';
            $j = $i + 1;
            while ($j < $count && $tokens[$j] !== ';' && $tokens[$j] !== '{') {
                if (is_array($tokens[$j]) && $tokens[$j][0] !== T_WHITESPACE) {
                    $name .= $tokens[$j][1];
                }
                $j++;
            }
            if ($tokens[$j] === '{') {
                throw new RuntimeException('Braced namespaces are not expected in bundled sources.');
            }
            if ($namespace !== null) {
                // A further `namespace X;` in the same file closes the previous block.
                $result = rtrim($result) . "\n}\n\n";
            }
            if ($scope && ($name === 'PhpParser' || strpos($name, 'PhpParser\\') === 0)) {
                $name = PREFIX . '\\' . $name;
            }
            $namespace = $name;
            $result .= 'namespace ' . $name . ' {';
            $i = $j;
            continue;
        }
        if ($scope && ($id === T_NAME_QUALIFIED || $id === T_NAME_FULLY_QUALIFIED)) {
            $text = prefixName($text);
        } elseif ($scope && $id === T_STRING && $text === 'PhpParser') {
            $text = PREFIX . '\\PhpParser';
        } elseif ($scope && $id === T_CONSTANT_ENCAPSED_STRING) {
            $text = preg_replace('/^([\'"])(\\\\{1,2})?PhpParser\\\\/', '$1$2' . PREFIX . '$2' . 'PhpParser\\', $text) ?? $text;
            if (strpos($text, '\\PhpParser\\') !== false && strpos($text, PREFIX) === false) {
                $text = str_replace('PhpParser\\', PREFIX . '\\\\PhpParser\\', $text);
            }
        }
        $result .= $text;
    }

    if ($namespace === null) {
        return "namespace {\n" . trim($result) . "\n}\n\n";
    }

    return trim($result) . "\n}\n\n";
}

function prefixName(string $name): string
{
    if (strpos($name, 'PhpParser\\') === 0) {
        return PREFIX . '\\' . $name;
    }
    if (strpos($name, '\\PhpParser\\') === 0) {
        return '\\' . PREFIX . $name;
    }

    return $name;
}

/**
 * A bundled file cannot `return` early at file scope (that would end the whole bundle).
 * php-parser's TokenPolyfill does `if (PHP >= 8) { class X extends \PhpToken {} return; }`;
 * turn it into an if/else so the remainder of the file becomes the else branch.
 */
function rewriteEarlyReturn(string $source): string
{
    $pattern = '/(if \(\\\\PHP_VERSION_ID >= 80000\) \{\s*class TokenPolyfill extends \\\\PhpToken \{\s*\})\s*return;\s*\}/';
    if (!preg_match($pattern, $source, $match, PREG_OFFSET_CAPTURE)) {
        return $source;
    }
    $start = $match[0][1];
    $end = $start + strlen($match[0][0]);

    return substr($source, 0, $start) . $match[1][0] . "\n} else {\n" . substr($source, $end) . "\n}\n";
}
