#!/usr/bin/env python3
"""#148: Show Definition end to end in a Debug app, with scratch data only.

Usage: sql-definition-screenshots.py /path/to/Runlet.app /path/to/output <postgres port> [/path/to/scratch]

Copies the `custom-driver` fixture to a scratch folder and adds an SQLite file (customers and
orders with a foreign key, a check, indexes, a trigger, and a view; neutral data) for a saved
connection. Creates `p148_` tables, an enum, and a view on the throwaway fixture PostgreSQL 14
(`scripts/setup-fixtures.sh databases`, user postgres, the fixture password; a scratch
RUNLET_DATA_DIR keeps it in memory) and saves a connection to it marked as production. Then
drives the app with RUNLET_DEBUG_STEPS: the Database pane, Show Definition of an SQLite table and
view, and of a PostgreSQL table after its production question. Checks that nothing changed. The
scratch folder (default /private/tmp/runlet-p148) is removed afterwards.
"""
from pathlib import Path
import shutil
import sqlite3
import subprocess
import sys

app = Path(sys.argv[1]).resolve()
out = Path(sys.argv[2]).resolve()
pg_port = sys.argv[3]
scratch = Path(sys.argv[4] if len(sys.argv) > 4 else "/private/tmp/runlet-p148")
root = Path(__file__).resolve().parent.parent
out.mkdir(parents=True, exist_ok=True)
shutil.rmtree(scratch, ignore_errors=True)
project = scratch / "acme"
shutil.copytree(root / "Tests/Fixtures/custom-driver", project, symlinks=True)
(project / "data").mkdir()
shop = sqlite3.connect(project / "data/shop.sqlite")
shop.executescript("""
CREATE TABLE customers (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    country TEXT NOT NULL DEFAULT 'NL'
);
CREATE TABLE orders (
    id INTEGER PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'paid', 'shipped')),
    total REAL NOT NULL DEFAULT 0,
    placed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX orders_customer ON orders (customer_id);
CREATE INDEX orders_status ON orders (status, placed_at);
CREATE TRIGGER orders_shipped AFTER UPDATE OF status ON orders
WHEN NEW.status = 'shipped'
BEGIN
    UPDATE customers SET country = country WHERE id = NEW.customer_id;
END;
CREATE VIEW open_orders AS
    SELECT o.id, c.name, o.total
    FROM orders o JOIN customers c ON c.id = o.customer_id
    WHERE o.status = 'open';
""")
shop.executemany("INSERT INTO customers (name, email, country) VALUES (?, ?, ?)", [(f"Customer {n}", f"customer{n}@example.test", ["NL", "DE", "FR"][n % 3]) for n in range(1, 41)])
shop.executemany("INSERT INTO orders (customer_id, status, total) VALUES (?, ?, ?)", [(n % 40 + 1, ["open", "paid", "shipped"][n % 3], round(10 + n * 1.5, 2)) for n in range(1, 121)])
shop.commit()
shop.close()

# PostgreSQL: the fixture server's p148_ objects, created again.
pg = f"pgsql:host=127.0.0.1;port={pg_port};dbname=shop"
setup = """
$p = new PDO($argv[1], 'postgres', 'runlet-fixture', [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
foreach ([
    'DROP VIEW IF EXISTS p148_open_orders', 'DROP TABLE IF EXISTS p148_orders, p148_customers', 'DROP TYPE IF EXISTS p148_status',
    "CREATE TYPE p148_status AS ENUM ('pending', 'paid', 'shipped')",
    "CREATE TABLE p148_customers (id SERIAL PRIMARY KEY, email VARCHAR(190) NOT NULL, country CHAR(2) DEFAULT 'UK', CONSTRAINT p148_customers_email UNIQUE (email))",
    "CREATE TABLE p148_orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id INT NOT NULL REFERENCES p148_customers(id) ON DELETE CASCADE, status p148_status NOT NULL DEFAULT 'pending', total NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0), note TEXT, placed_at TIMESTAMPTZ NOT NULL DEFAULT now())",
    'CREATE INDEX p148_orders_status ON p148_orders (status, customer_id)',
    'CREATE UNIQUE INDEX p148_orders_note ON p148_orders (lower(note)) WHERE note IS NOT NULL',
    "COMMENT ON TABLE p148_orders IS 'Orders placed by customers'",
    "COMMENT ON COLUMN p148_orders.total IS 'In euros'",
    "CREATE VIEW p148_open_orders AS SELECT o.id, c.email, o.total FROM p148_orders o JOIN p148_customers c ON c.id = o.customer_id WHERE o.status <> 'shipped'",
    "INSERT INTO p148_customers (email) VALUES ('a@example.test'), ('b@example.test')",
] as $sql) { $p->exec($sql); }
"""
subprocess.run(["php", "-r", setup, pg], check=True)

query = scratch / "orders.sql"
query.write_text("-- Open orders per customer\nSELECT c.name, COUNT(*) AS orders\nFROM orders o\nJOIN customers c ON c.id = o.customer_id\nWHERE o.status = 'open'\nGROUP BY c.name;\n")

steps = [
    "ghost", "scale:2", "frame:1440x860", "appearance:light", f"project:{project}", "wait",
    "perform:file.newSQLTab", "db-new:Shop|sqlite|||data/shop.sqlite", "db-use:Shop", f"code:{query}", "wait",
    "inspector:database", "sql-schema:load", "wait", "schema-expand:orders", "wait", "shot:definition-explorer",
    # SQLite: a table with its indexes and trigger, then a view.
    "schema-definition:orders", "wait", "wait", "schema-definition-state", "shot:definition-sqlite-table",
    "schema-definition:open_orders", "wait", "wait", "schema-definition-state", "shot:definition-sqlite-view",
    # PostgreSQL, marked production: Load Schema and Show Definition ask first.
    "perform:file.newSQLTab", f"db-new:Analytics|pgsql|127.0.0.1|{pg_port}|shop|postgres|runlet-fixture|production", "db-use:Analytics", "wait",
    "sql-schema:load", "wait", "confirm", "wait", "wait", "schema-search:p148", "wait",
    "schema-definition:p148_orders", "wait", "shot:definition-production-question", "confirm", "wait", "wait", "schema-definition-state",
    "shot:definition-postgres", "appearance:dark", "wait", "shot:definition-postgres-dark", "appearance:light",
]
log_path = out / "capture.log"
log_path.write_text("")
subprocess.run(["open", "-g", "-j", "-n", "-W",
                "--env", f"RUNLET_DATA_DIR={scratch / 'data'}", "--env", f"RUNLET_SNAPSHOT_DIR={out}",
                "--env", f"RUNLET_DEBUG_STEPS={','.join(steps)}", "--env", "SSH_AUTH_SOCK=",
                "--stderr", str(log_path), str(app)], check=True)
log = log_path.read_text()
states = [line for line in log.splitlines() if "RUNLET_DEBUG_STATE: schema-definition" in line or "RUNLET_DEBUG_STATE: db-" in line]
print("\n".join(states))
assert "RUNLET_DEBUG_STEPS: done" in log, log
definitions = [line for line in states if "schema-definition:" in line]
assert "orders table via sqlite_master" in definitions[0] and "orders (definition) [sql]" in definitions[0], definitions[0]
assert "open_orders view via sqlite_master" in definitions[1], definitions[1]
assert "p148_orders table via pg_catalog (reconstructed)" in definitions[2], definitions[2]
count = subprocess.run(["php", "-r", "echo (new PDO($argv[1], 'postgres', 'runlet-fixture'))->query('SELECT COUNT(*) FROM p148_customers')->fetchColumn();", pg], capture_output=True, text=True, check=True).stdout
assert count == "2", f"nothing ran but the catalog read: {count}"
shots = sorted(out.glob("definition-*.png"))
assert len(shots) == 6, shots
shutil.rmtree(scratch)
print("ok:", [p.name for p in shots])
